import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";

export const metadata: Metadata = {

    title: "Tenebra | Alt your look.",
    description: "Generated by create next app"

};

export default function RootLayout({ children }: Readonly<{
  
    children: React.ReactNode;

}>) {

    return (

        <html lang="en">
            
            <body className="antialiased bg-background text-text-primary">
                
                <Header/>
                {children}
                <Footer/>
            
            </body>
        
        </html>

    );

}
